name: C/C++ CI

on:
  push:
    branches: [ "draw" ]
  pull_request:
    branches: [ "draw" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xorg-dev libglfw3-dev
    - name: Run run_game tests
      run: |
        cd draw_tests
        make all
        ./draw_tests
