name: C/C++ CI

on:
  push:
    branches: [ "parsing_file" ]
  pull_request:
    branches: [ "parsing_file" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xorg-dev libglfw3-dev
    - name: Run parser tests
      run: |
        cd parsing_tests
        make all
        ./parser_tests
