name: C/C++ CI

on:
  push:
    branches: [ "validate_map" ]
  pull_request:
    branches: [ "validate_map" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xorg-dev libglfw3-dev
    - name: Run validation tests
      run: |
        cd validate_tests
        make all
        ./validate_tests
    - name: Finish
      if: always()
      run: |
        echo "Validation tests completed."
        